FORMAT: 1A

# UBox

Microservices for users

## Users [/api/users]

### List users [GET]

+ Response 200 (application/json)

        {
          "meta": {
            "page": 1,
            "size": 10,
            "total": 1
          },
          "data": [
            "verified": false,
            "_id": "5ecf208f7e372416b23669c2",
            "name": "Gabriel Rufino",
            "email": "gabrielruufinooo@gmail.com",
            "username": "gabrielrufinoo",
            "__v": 0
          ]
        }

### Create new user [POST]

+ name (string) - User name
+ email (string) - User email

+ Request  (application/json)

        {
          "name": "Gabriel Rufino",
          "email": "contato@gabrielrufino.com",
          "username": "gabrielrufino",
          "password": "12345678"
        }

+ Response 201 (application/json)

        {
          "success": "User created"
        }

## User [/api/users/{user_id}]

Endpoint to unique user actions

### Detail user [GET]

+ Response 200 (application/json)

        {
          "verified": false,
          "_id": "5ecf208f7e372416b23669c2",
          "name": "Gabriel Rufino",
          "email": "gabrielruufinooo@gmail.com",
          "username": "gabrielrufinoo",
          "__v": 0
        }

+ Response 404 (application/json)

        {
          "error": "User not found"
        }

### Update user [PATCH]

+ Response 200 (application/json)

        {
          "id": "11d6525e-827a-47cd-b707-cc41155df58b",
          "name": "Gabriel Rufino"
        }

+ Response 200 (application/json)

        {
          "id": "11d6525e-827a-47cd-b707-cc41155df58b",
          "name": "Gabriel Rufino"
        }

### Delete user [DELETE]

+ Response 200 (application/json)

        {
          "success": "User deleted"
        }

+ Response 404 (application/json)

        {
          "error": "User not found"
        }

## Tokens [/api/tokens]

### Create token [POST]

+ username (string) - username
+ password (string) - password

+ Request  (application/json)

        {
          "username": "gabrielrufino",
          "password": "12345678"
        }

+ Response 201 (application/json)

        {
          "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAvIiwic3ViIjoiNWVkMDQ1ZjgzYzU1Njk1M2I4YTkyN2ExIiwiaWF0IjoxNTkwNzEzODg4LCJleHAiOjE1OTA3MTc0ODh9.vv63_7FjITYWyoT-ykElhtrfgMKUQmuNZgbScx903k0"
        }
